### ISSUE TITLE
what is the difference between of this package and common regular expression

### ISSUE THREAD

**Issue by xilinniao123** [rouseway/patmatch#1]
你好：
感谢分享，但是发现这个包的功能普通正则也能实现，请问这个包比普通正则的优势是什么？谢谢

**Comment by rouseway** [comment]
这个是把多个模板加载到一个引擎上，对文本进行一次遍历就可实现匹配；而正则表达式是一个表达式对应一个引擎，要执行所有的规则，需要遍历多次文本。
